# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-27 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0015_auto_20161224_0054'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addrobj',
            table='fias_addrobj',
        ),
    ]
