# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-27 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0016_auto_20170727_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='stead',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
